### ISSUE TITLE
how to get all treenodes into a <ul><li>node</li></ul>with auto indentation??

### ISSUE THREAD

**Issue by robinclark007** [matperez/yii2-materialized-path#6]
i mean how can I create a dropdown list of the treenode

**Comment by matperez** [comment]
just walk recursively to all descendants and make a list. you can use the "level" attribute to count an adjustment. take a look at https://github.com/matperez/yii2-materialized-path/blob/master/tests/unit/MaterializedPathBehaviorTest.php#L148

**Comment by robinclark007** [comment]
@matperez sorry  i didn't walk throught the test cases?
but the recursively way involving read the db recursively too???

**Comment by matperez** [comment]
@robinclark007 no, the data is already in memory. it reads the whole subtree at once.

**Comment by robinclark007** [comment]
@matperez now i find other problem.
because the catalog is unlimited.

---

```
        $roots = Tree::find()->roots()->all();

        $items = [
            //$root->id => $root->label,
        ];

        foreach ($roots as $root) {
          $label = str_repeat('**', $root->level).$root->name;
          $items[$root->id] = $label;

          foreach ($root->children as $child) {

              $label = str_repeat(' ', $child->level).$child->name;
              $items[$child->id] = $label;

              if ($child->hasChildren()) {

                  foreach ($child->children as $subChild) {
                      $label = str_repeat(' ', $subChild->level).$subChild->name;
                      $items[$subChild->id] = $label;
                  }
              }
          }
        };
```

---

with this code , only three level of data will be put into the $items array.
but if I have 8 level of catalog, so it won't work.does that means i have to 

continue write the foreach statement again and again??
that does not make sense at all.

**Comment by robinclark007** [comment]
@matperez 
i solved the problem by writing a recursive function inside the controller 

may be you can put below function into the test cases???cause it's a very common task of perform this kind of operation..

---

```
protected $items;

protected function treeRecursion($roots){

  foreach ($roots as $root) {

    $label = str_repeat('**', $root->level).$root->name;
    $this->items[$root->id] = $label;

    if($root->hasChildren()){
      $this->treeRecursion($root->children);
    }
  }
}
```

---

then i use this function to generate the result

---

```
        $roots = Tree::find()->roots()->all();
        $this->treeRecursion($roots);
        $result = $this->items;
```

---

I have to put the $item outside the function ,if i put the $item in the function didn't get the result expected.
